global using System.Globalization;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Text.RegularExpressions;
global using Cosmos.Text.Joiners;
global using Cosmos.Text.Splitters;
global using Cosmos.Serialization;
global using Cosmos.Conversions;
global using Cosmos.Conversions.ObjectMappingServices;